Repository starcoinorg/starcoin, pull requests merged in 2020-10, with the labels that each got.

#1428 [ci] Support auto rebase and merge.
  .github/workflows/auto_merge.yml
  .github/workflows/autorebase.yml
  .github/workflows/benchmark.yml
  .github/workflows/rebase.yaml
  .github/workflows/release_asset.yml
Labels: automerge

#1441 some ue update
  cmd/starcoin/src/dev/execute_cmd.rs
  cmd/starcoin/src/view.rs
  commons/scmd/src/context.rs
  commons/scmd/src/result.rs
  vm/types/src/account_config/events/dao.rs
  vm/types/src/account_config/events/mod.rs
Labels: automerge, autorebase:opt-in

#1443 [stdlib]Adjust gas limit
  chain/open-block/src/lib.rs
  chain/src/chain.rs
  chain/src/tests/block_test_utils.rs
  chain/src/tests/test_block_chain.rs
  core/genesis/generated/dev/genesis
  core/genesis/generated/halley/genesis
  core/genesis/generated/main/genesis
  etc/starcoin_types.yml
  executor/benchmark/src/lib.rs
  executor/src/error_code_test.rs
  executor/src/executor_test.rs
  executor/src/stdlib_test/module_upgrade_test.rs
  miner/src/create_block_template/test_create_block_template.rs
  txpool/src/test.rs
  types/src/block.rs
  vm/functional-tests/src/config/block_metadata.rs
  vm/functional-tests/src/executor.rs
  vm/functional-tests/tests/testsuite/on_chain_config/adjust_epoch_block_time_max.move
  vm/functional-tests/tests/testsuite/on_chain_config/adjust_epoch_block_time_min.move
  vm/functional-tests/tests/testsuite/on_chain_config/adjust_gas_limit.move
  vm/stdlib/compiled/latest/init_scripts/genesis_init.mv
  vm/stdlib/compiled/latest/stdlib/17_ConsensusConfig.mv
  vm/stdlib/compiled/latest/stdlib/18_Block.mv
  vm/stdlib/compiled/latest/stdlib/43_TransactionManager.mv
  vm/stdlib/modules/Block.move
  vm/stdlib/modules/ConsensusConfig.move
  vm/stdlib/modules/TransactionManager.move
  vm/stdlib/modules/doc/Block.md
  vm/stdlib/modules/doc/ConsensusConfig.md
  vm/stdlib/modules/doc/TransactionManager.md
  vm/types/src/block_metadata.rs
  vm/types/src/on_chain_config/consensus_config.rs
  vm/types/src/proptest_types.rs
  vm/vm-runtime/src/starcoin_vm.rs
Labels: automerge, autorebase:opt-in

#1451 Feature/accumulator storage refactor
  .github/workflows/auto_merge.yml
  Cargo.lock
  account/lib/src/account_storage.rs
  benchmarks/benches/bench_storage.rs
  chain/open-block/src/lib.rs
  chain/src/chain.rs
  chain/src/tests/block_test_utils.rs
  core/accumulator/Cargo.toml
  core/accumulator/src/accumulator_info.rs
  core/accumulator/src/accumulator_test.rs
  core/accumulator/src/lib.rs
  core/accumulator/src/node.rs
  core/accumulator/src/tree.rs
  core/accumulator/src/tree_store/mock.rs
  core/accumulator/src/tree_store/mod.rs
  core/genesis/src/lib.rs
  network-rpc/src/rpc.rs
  storage/Cargo.toml
  storage/src/accumulator/mod.rs
  storage/src/batch/mod.rs
  storage/src/block/mod.rs
  storage/src/block_info/mod.rs
  storage/src/chain_info/mod.rs
  storage/src/contract_event.rs
  storage/src/lib.rs
  storage/src/state_node/mod.rs
  storage/src/storage.rs
  storage/src/storage_macros.rs
  storage/src/tests/test_accumulator.rs
  storage/src/tests/test_batch.rs
  storage/src/tests/test_storage.rs
  storage/src/transaction/mod.rs
  storage/src/transaction_info/mod.rs
  sync/src/block_connector/mod.rs
  sync/src/state_sync/mod.rs
  test-helper/src/dummy_network_service.rs
Labels: autorebase:opt-in

#1458 [consensus] fix node_info now milliseconds bug
  consensus/src/consensus.rs
  rpc/api/src/node/mod.rs
Labels: ready

#1444 improve dao
  core/genesis/generated/dev/genesis
  core/genesis/generated/halley/genesis
  core/genesis/generated/main/genesis
  core/genesis/generated/proxima/genesis
  executor/src/stdlib_test/module_upgrade_test.rs
  vm/functional-tests/tests/testsuite/dao/test_dao_propose.move
  vm/functional-tests/tests/testsuite/on_chain_config/test_onchain_config_dao.move
  vm/functional-tests/tests/testsuite/token/init_stc.move
  vm/stdlib/compiled/latest/init_scripts/genesis_init.mv
  vm/stdlib/compiled/latest/stdlib/20_Dao.mv
  vm/stdlib/compiled/latest/stdlib/21_UpgradeModuleDaoProposal.mv
  vm/stdlib/compiled/latest/stdlib/24_OnChainConfigDao.mv
  vm/stdlib/compiled/latest/stdlib/25_ModifyDaoConfigProposal.mv
  vm/stdlib/compiled/latest/stdlib/26_STC.mv
  vm/stdlib/compiled/latest/stdlib/37_MintDaoProposal.mv
  vm/stdlib/compiled/latest/transaction_scripts/abi/propose_modify_dao_config.abi
  vm/stdlib/compiled/latest/transaction_scripts/abi/propose_module_upgrade.abi
  vm/stdlib/compiled/latest/transaction_scripts/propose_modify_dao_config.mv
  vm/stdlib/compiled/latest/transaction_scripts/propose_module_upgrade.mv
  vm/stdlib/init_scripts/genesis_init.move
  vm/stdlib/modules/Dao.move
  vm/stdlib/modules/MintDaoProposal.move
  vm/stdlib/modules/ModifyDaoConfigProposal.move
  vm/stdlib/modules/OnChainConfigDao.move
  vm/stdlib/modules/STC.move
  vm/stdlib/modules/UpgradeModuleDaoProposal.move
  vm/stdlib/modules/doc/Dao.md
  vm/stdlib/modules/doc/MintDaoProposal.md
  vm/stdlib/modules/doc/ModifyDaoConfigProposal.md
  vm/stdlib/modules/doc/OnChainConfigDao.md
  vm/stdlib/modules/doc/STC.md
  vm/stdlib/modules/doc/UpgradeModuleDaoProposal.md
  vm/stdlib/src/lib.rs
  vm/stdlib/transaction_scripts/doc/genesis_init.md
  vm/stdlib/transaction_scripts/doc/propose_modify_dao_config.md
  vm/stdlib/transaction_scripts/doc/propose_module_upgrade.md
  vm/stdlib/transaction_scripts/propose_modify_dao_config.move
  vm/stdlib/transaction_scripts/propose_module_upgrade.move
  vm/transaction-builder/src/lib.rs
  vm/types/src/dao_config.rs
  vm/types/src/genesis_config.rs
  vm/types/src/lib.rs
Labels: ready

#1461 [accumulator] Enhancement and optimize accumulator
  core/accumulator/src/accumulator_test.rs
  core/accumulator/src/lib.rs
  core/accumulator/src/tree.rs
Labels: ready

#1456 [spec] Account, ConsensusConfig, Authenticator, etc
  vm/move-prover/docs/prover-guide.md
  vm/stdlib/modules/Account.move
  vm/stdlib/modules/Authenticator.move
  vm/stdlib/modules/Config.move
  vm/stdlib/modules/ConsensusConfig.move
  vm/stdlib/modules/Math.move
  vm/stdlib/modules/STC.move
  vm/stdlib/modules/SharedEd25519PublicKey.move
  vm/stdlib/modules/Timestamp.move
  vm/stdlib/modules/Token.move
  vm/stdlib/modules/doc/Account.md
  vm/stdlib/modules/doc/Authenticator.md
  vm/stdlib/modules/doc/Config.md
  vm/stdlib/modules/doc/ConsensusConfig.md
  vm/stdlib/modules/doc/Math.md
  vm/stdlib/modules/doc/STC.md
  vm/stdlib/modules/doc/SharedEd25519PublicKey.md
  vm/stdlib/modules/doc/Timestamp.md
  vm/stdlib/modules/doc/Token.md
Labels: ready

#1460 [consensus] timeService refactor for now seconds and milliseconds
  benchmarks/src/lib.rs
  chain/src/chain.rs
  chain/src/tests/block_test_utils.rs
  chain/src/tests/test_block_chain.rs
  chain/src/tests/test_opened_block.rs
  consensus/src/consensus.rs
  consensus/src/consensus_test.rs
  consensus/src/dev.rs
  consensus/src/dummy.rs
  consensus/src/time.rs
  executor/benchmark/src/lib.rs
  executor/src/error_code_test.rs
  executor/src/executor_test.rs
  executor/src/stdlib_test/module_upgrade_test.rs
  miner/src/create_block_template/mod.rs
  rpc/api/src/node/mod.rs
  rpc/server/src/module/pubsub/tests.rs
  sync/tests/txn_sync_test.rs
  txpool/src/test.rs
  txpool/src/tx_pool_service_impl.rs
Labels: ready

#1462 [stdlid]TransactionTimeoutConfig
  core/genesis/generated/dev/genesis
  core/genesis/generated/halley/genesis
  core/genesis/generated/main/genesis
  core/genesis/generated/proxima/genesis
  vm/stdlib/compiled/latest/init_scripts/genesis_init.mv
  vm/stdlib/compiled/latest/stdlib/22_TransactionTimeoutConfig.mv
  vm/stdlib/compiled/latest/stdlib/23_RewardConfig.mv
  vm/stdlib/compiled/latest/stdlib/23_TransactionPublishOption.mv
  vm/stdlib/compiled/latest/stdlib/24_RewardConfig.mv
  vm/stdlib/compiled/latest/stdlib/25_OnChainConfigDao.mv
  vm/stdlib/compiled/latest/stdlib/26_ModifyDaoConfigProposal.mv
  vm/stdlib/compiled/latest/stdlib/26_STC.mv
  vm/stdlib/compiled/latest/stdlib/27_STC.mv
  vm/stdlib/compiled/latest/stdlib/28_TransactionFee.mv
  vm/stdlib/compiled/latest/stdlib/29_Hash.mv
  vm/stdlib/compiled/latest/stdlib/30_Authenticator.mv
  vm/stdlib/compiled/latest/stdlib/31_Account.mv
  vm/stdlib/compiled/latest/stdlib/32_BlockReward.mv
  vm/stdlib/compiled/latest/stdlib/33_Box.mv
  vm/stdlib/compiled/latest/stdlib/34_ChainId.mv
  vm/stdlib/compiled/latest/stdlib/35_Compare.mv
  vm/stdlib/compiled/latest/stdlib/36_ConsensusStrategy.mv
  vm/stdlib/compiled/latest/stdlib/37_DummyToken.mv
  vm/stdlib/compiled/latest/stdlib/38_MintDaoProposal.mv
  vm/stdlib/compiled/latest/stdlib/39_Offer.mv
  vm/stdlib/compiled/latest/stdlib/40_Signature.mv
  vm/stdlib/compiled/latest/stdlib/41_SharedEd25519PublicKey.mv
  vm/stdlib/compiled/latest/stdlib/42_SortedLinkedList.mv
  vm/stdlib/compiled/latest/stdlib/43_TokenLockPool.mv
  vm/stdlib/compiled/latest/stdlib/43_TransactionTimeout.mv
  vm/stdlib/compiled/latest/stdlib/44_TransactionTimeout.mv
  vm/stdlib/compiled/latest/stdlib/45_TransactionManager.mv
  vm/stdlib/init_scripts/genesis_init.move
  vm/stdlib/modules/RewardConfig.move
  vm/stdlib/modules/STC.move
  vm/stdlib/modules/TransactionTimeout.move
  vm/stdlib/modules/TransactionTimeoutConfig.move
  vm/stdlib/modules/doc/RewardConfig.md
  vm/stdlib/modules/doc/STC.md
  vm/stdlib/modules/doc/TransactionTimeout.md
  vm/stdlib/modules/doc/TransactionTimeoutConfig.md
  vm/stdlib/transaction_scripts/doc/genesis_init.md
  vm/transaction-builder/src/lib.rs
  vm/types/src/genesis_config.rs
Labels: ready

#1459 set env BOOGIE_EXE and Z3_EXE for ci
  scripts/auto_rerun_test.sh
  vm/move-prover/scripts/linux/install-boogie.sh
  vm/move-prover/scripts/linux/install-z3.sh
  vm/move-prover/scripts/macos/install-boogie.sh
Labels: ready

#1463 Implement new network rpc api and BlockAccumulatorSyncTask
  Cargo.lock
  chain/api/src/chain.rs
  chain/api/src/message.rs
  chain/api/src/service.rs
  chain/mock/src/lib.rs
  chain/mock/src/mock_chain_service.rs
  chain/service/src/chain_service.rs
  chain/src/chain.rs
  chain/src/tests/block_test_utils.rs
  cmd/generator/src/gen_data.rs
  cmd/generator/src/gen_genesis.rs
  cmd/generator/src/lib.rs
  core/accumulator/src/tree_store/mod.rs
  core/genesis/src/lib.rs
  network-rpc/api/src/lib.rs
  network-rpc/src/rpc.rs
  network-rpc/src/tests.rs
  node/Cargo.toml
  node/src/lib.rs
  node/src/node.rs
  storage/src/block/mod.rs
  storage/src/lib.rs
  sync/Cargo.toml
  sync/src/block_connector/block_connect_test.rs
  sync/src/block_connector/mod.rs
  sync/src/block_connector/test_illegal_block.rs
  sync/src/block_connector/write_block_chain.rs
  sync/src/block_sync/mod.rs
  sync/src/block_sync/test_block_sync.rs
  sync/src/download.rs
  sync/src/helper.rs
  sync/src/lib.rs
  sync/src/state_sync/mod.rs
  sync/src/task.rs
  sync/src/verified_rpc_client.rs
  sync/tests/accumulator_sync_test.rs
  sync/tests/txn_sync_test.rs
Labels: ready

#1453 [onchain-config]update consensus_config add strategy
  core/genesis/generated/dev/genesis
  core/genesis/generated/halley/genesis
  core/genesis/generated/main/genesis
  core/genesis/generated/proxima/genesis
  vm/stdlib/compiled/latest/init_scripts/genesis_init.mv
  vm/stdlib/compiled/latest/stdlib/17_ConsensusConfig.mv
  vm/stdlib/init_scripts/genesis_init.move
  vm/stdlib/modules/ConsensusConfig.move
  vm/stdlib/modules/doc/ConsensusConfig.md
  vm/stdlib/transaction_scripts/doc/genesis_init.md
  vm/transaction-builder/src/lib.rs
  vm/types/src/genesis_config.rs
  vm/types/src/on_chain_config/consensus_config.rs
Labels: ready

#1468 Feature/timeservice refactor
  benchmarks/src/chain.rs
  benchmarks/src/lib.rs
  chain/mock/src/mock_chain.rs
  chain/service/src/chain_service.rs
  chain/src/chain.rs
  chain/src/tests/block_test_utils.rs
  chain/src/tests/test_block_chain.rs
  chain/src/tests/test_opened_block.rs
  consensus/src/argon.rs
  consensus/src/cn.rs
  consensus/src/consensus.rs
  consensus/src/consensus_test.rs
  consensus/src/dev.rs
  consensus/src/dummy.rs
  consensus/src/keccak.rs
  consensus/src/lib.rs
  consensus/src/time.rs
  core/genesis/generated/dev/genesis
  core/genesis/src/lib.rs
  executor/benchmark/src/lib.rs
  executor/src/error_code_test.rs
  executor/src/executor_test.rs
  executor/src/stdlib_test/module_upgrade_test.rs
  miner/src/create_block_template/mod.rs
  miner/src/create_block_template/test_create_block_template.rs
  miner/src/lib.rs
  rpc/api/src/node/mod.rs
  rpc/server/src/module/pubsub/tests.rs
  sync/src/block_connector/test_illegal_block.rs
  sync/src/block_connector/test_write_block_chain.rs
  sync/src/block_connector/write_block_chain.rs
  sync/tests/txn_sync_test.rs
  test-helper/src/chain.rs
  txpool/src/tx_pool_service_impl.rs
  types/src/block.rs
  vm/types/src/genesis_config.rs
  vm/types/src/lib.rs
  vm/types/src/time.rs
Labels: auto_merge_failed, ready_to_merge

#1476 [stdlib]Config script
  core/genesis/generated/dev/genesis
  core/genesis/generated/halley/genesis
  core/genesis/generated/main/genesis
  core/genesis/generated/proxima/genesis
  vm/stdlib/compiled/0.4/stdlib/15_Version.mv
  vm/stdlib/compiled/latest/stdlib/14_Version.mv
  vm/stdlib/compiled/latest/stdlib/22_TransactionPublishOption.mv
  vm/stdlib/compiled/latest/stdlib/44_TransactionTimeout.mv
  vm/stdlib/compiled/latest/transaction_scripts/abi/add_to_script_allow_list.abi
  vm/stdlib/compiled/latest/transaction_scripts/abi/execute_proposal.abi
  vm/stdlib/compiled/latest/transaction_scripts/abi/set_open_module.abi
  vm/stdlib/compiled/latest/transaction_scripts/abi/set_open_script.abi
  vm/stdlib/compiled/latest/transaction_scripts/abi/update_consensus_config_proposal.abi
  vm/stdlib/compiled/latest/transaction_scripts/abi/update_reward_config_proposal.abi
  vm/stdlib/compiled/latest/transaction_scripts/abi/update_txn_publish_option_proposal.abi
  vm/stdlib/compiled/latest/transaction_scripts/abi/update_txn_timeout_config_proposal.abi
  vm/stdlib/compiled/latest/transaction_scripts/abi/update_version_proposal.abi
  vm/stdlib/compiled/latest/transaction_scripts/abi/update_vm_config_proposal.abi
  vm/stdlib/compiled/latest/transaction_scripts/add_to_script_allow_list.mv
  vm/stdlib/compiled/latest/transaction_scripts/execute_proposal.mv
  vm/stdlib/compiled/latest/transaction_scripts/set_open_module.mv
  vm/stdlib/compiled/latest/transaction_scripts/set_open_script.mv
  vm/stdlib/compiled/latest/transaction_scripts/update_consensus_config_proposal.mv
  vm/stdlib/compiled/latest/transaction_scripts/update_reward_config_proposal.mv
  vm/stdlib/compiled/latest/transaction_scripts/update_txn_publish_option_proposal.mv
  vm/stdlib/compiled/latest/transaction_scripts/update_txn_timeout_config_proposal.mv
  vm/stdlib/compiled/latest/transaction_scripts/update_version_proposal.mv
  vm/stdlib/compiled/latest/transaction_scripts/update_vm_config_proposal.mv
  vm/stdlib/modules/TransactionPublishOption.move
  vm/stdlib/modules/Version.move
  vm/stdlib/modules/doc/Errors.md
  vm/stdlib/modules/doc/TransactionPublishOption.md
  vm/stdlib/modules/doc/TransactionTimeout.md
  vm/stdlib/modules/doc/Version.md
  vm/stdlib/src/transaction_scripts.rs
  vm/stdlib/transaction_scripts/add_to_script_allow_list.move
  vm/stdlib/transaction_scripts/doc/add_to_script_allow_list.md
  vm/stdlib/transaction_scripts/doc/execute_proposal.md
  vm/stdlib/transaction_scripts/doc/set_open_module.md
  vm/stdlib/transaction_scripts/doc/set_open_script.md
  vm/stdlib/transaction_scripts/doc/update_consensus_config_proposal.md
  vm/stdlib/transaction_scripts/doc/update_reward_config_proposal.md
  vm/stdlib/transaction_scripts/doc/update_txn_publish_option_proposal.md
  vm/stdlib/transaction_scripts/doc/update_txn_timeout_config_proposal.md
  vm/stdlib/transaction_scripts/doc/update_version_proposal.md
  vm/stdlib/transaction_scripts/doc/update_vm_config_proposal.md
  vm/stdlib/transaction_scripts/execute_proposal.move
  vm/stdlib/transaction_scripts/set_open_module.move
  vm/stdlib/transaction_scripts/set_open_script.move
  vm/stdlib/transaction_scripts/update_consensus_config_proposal.move
  vm/stdlib/transaction_scripts/update_reward_config_proposal.move
  vm/stdlib/transaction_scripts/update_txn_publish_option_proposal.move
  vm/stdlib/transaction_scripts/update_txn_timeout_config_proposal.move
  vm/stdlib/transaction_scripts/update_version_proposal.move
  vm/stdlib/transaction_scripts/update_vm_config_proposal.move
Labels: ready_to_merge

#1479 cryptonight-rs: Remove boost dep
  consensus/cryptonight-rs/build.rs
  consensus/cryptonight-rs/ext/chacha.c
  consensus/cryptonight-rs/ext/chacha.h
  consensus/cryptonight-rs/ext/common/warnings.h
  consensus/cryptonight-rs/ext/hash.h
Labels: ready_to_merge

#1480 [ready_to_merge] fix block time target
  chain/src/chain.rs
  chain/src/tests/test_block_chain.rs
  cmd/miner_client/src/worker.rs
  cmd/starcoin/src/cli_state.rs
  cmd/starcoin/src/main.rs
  config/src/lib.rs
  consensus/src/difficulty.rs
  consensus/src/dummy.rs
  core/genesis/generated/dev/genesis
  core/genesis/generated/halley/genesis
  core/genesis/generated/proxima/genesis
  miner/src/create_block_template/test_create_block_template.rs
  miner/src/lib.rs
  miner/src/miner.rs
  node/src/node.rs
  rpc/server/src/module/pubsub/tests.rs
  storage/src/lib.rs
  storage/src/transaction_info/mod.rs
  sync/src/block_connector/test_illegal_block.rs
  sync/src/block_connector/test_write_block_chain.rs
  test-helper/src/chain.rs
  testsuite/features/cmd.feature
  testsuite/tests/steps/cmd.rs
  types/src/block.rs
  vm/functional-tests/Cargo.toml
  vm/types/src/genesis_config.rs
  vm/types/src/on_chain_config/consensus_config.rs
Labels: ready_to_merge

#1493 Update gensis for cnr config && fix hash rate info
  cmd/miner_client/src/worker.rs
  consensus/cryptonight-rs/benches/bench.rs
  core/genesis/generated/halley/genesis
  core/genesis/generated/main/genesis
  core/genesis/generated/proxima/genesis
  vm/types/src/genesis_config.rs
Labels: ready_to_merge

#1472 [ci] Remove auto_merge/autorebase/rebase workflows
  .github/workflows/auto_merge.yml
  .github/workflows/autorebase.yml
  .github/workflows/rebase.yaml
Labels: ready_to_merge

#1492 [stdlib]Spec for BlockReward
  core/genesis/generated/dev/genesis
  core/genesis/generated/halley/genesis
  core/genesis/generated/main/genesis
  core/genesis/generated/proxima/genesis
  vm/stdlib/compiled/latest/stdlib/23_RewardConfig.mv
  vm/stdlib/compiled/latest/stdlib/31_BlockReward.mv
  vm/stdlib/modules/BlockReward.move
  vm/stdlib/modules/RewardConfig.move
  vm/stdlib/modules/doc/BlockReward.md
  vm/stdlib/modules/doc/RewardConfig.md
Labels: auto_merge_failed, ready_to_merge

#1496 [miner] Refactor miner and chain.
  Cargo.lock
  chain/api/src/message.rs
  chain/api/src/service.rs
  chain/service/src/chain_service.rs
  chain/src/chain.rs
  commons/service-registry/src/service.rs
  miner/src/lib.rs
  miner/src/miner.rs
  miner/src/task.rs
  network/src/message_processor.rs
  node/src/lib.rs
  node/src/node.rs
  node/tests/test_node_run.rs
  sync/Cargo.toml
  sync/src/download.rs
  sync/tests/accumulator_sync_test.rs
  sync/tests/full_sync_test.rs
  sync/tests/test_sync/mod.rs
Labels: ready_to_merge

#1499 spec for dao module
  core/genesis/generated/dev/genesis
  core/genesis/generated/halley/genesis
  core/genesis/generated/main/genesis
  core/genesis/generated/proxima/genesis
  vm/stdlib/compiled/latest/stdlib/19_Dao.mv
  vm/stdlib/modules/Dao.move
  vm/stdlib/modules/doc/Dao.md
Labels: ready_to_merge

#1500 stdlib: Fix new_consensus_config argument error
  core/genesis/generated/dev/genesis
  core/genesis/generated/halley/genesis
  core/genesis/generated/main/genesis
  core/genesis/generated/proxima/genesis
  vm/stdlib/compiled/latest/stdlib/16_ConsensusConfig.mv
  vm/stdlib/modules/ConsensusConfig.move
  vm/stdlib/modules/doc/ConsensusConfig.md
Labels: ready_to_merge

#1510 stdlib: create account using auth_key not public key
  Cargo.lock
  benchmarks/src/lib.rs
  chain/open-block/src/lib.rs
  chain/src/tests/block_test_utils.rs
  chain/src/tests/test_block_chain.rs
  chain/src/tests/test_opened_block.rs
  cmd/faucet/Cargo.toml
  cmd/faucet/src/faucet.rs
  cmd/starcoin/src/account/transfer_cmd.rs
  cmd/starcoin/src/debug/gen_txn_cmd.rs
  cmd/starcoin/src/dev/get_coin_cmd.rs
  cmd/tx-factory/src/main.rs
  cmd/tx-factory/src/txn_generator.rs
  core/genesis/generated/dev/genesis
  core/genesis/generated/halley/genesis
  core/genesis/generated/main/genesis
  core/genesis/generated/proxima/genesis
  dataformat-generator/build.rs
  etc/starcoin_types.yml
  executor/benchmark/src/lib.rs
  executor/src/error_code_test.rs
  executor/src/executor_test.rs
  executor/src/stdlib_test/module_upgrade_test.rs
  rpc/server/src/module/pubsub/tests.rs
  sync/tests/txn_sync_test.rs
  testsuite/tests/steps/node.rs
  testsuite/tests/steps/transaction.rs
  txpool/src/test.rs
  types/src/block.rs
  vm/functional-tests/src/account.rs
  vm/functional-tests/src/config/block_metadata.rs
  vm/functional-tests/tests/testsuite/account/basic.move
  vm/functional-tests/tests/testsuite/token/create_account_with_token.move
  vm/stdlib/compiled/latest/error_descriptions/error_descriptions.errmap
  vm/stdlib/compiled/latest/stdlib/30_Account.mv
  vm/stdlib/compiled/latest/stdlib/31_BlockReward.mv
  vm/stdlib/compiled/latest/transaction_scripts/abi/create_account.abi
  vm/stdlib/compiled/latest/transaction_scripts/abi/peer_to_peer.abi
  vm/stdlib/compiled/latest/transaction_scripts/abi/peer_to_peer_with_metadata.abi
  vm/stdlib/compiled/latest/transaction_scripts/create_account.mv
  vm/stdlib/compiled/latest/transaction_scripts/peer_to_peer.mv
  vm/stdlib/compiled/latest/transaction_scripts/peer_to_peer_with_metadata.mv
  vm/stdlib/modules/Account.move
  vm/stdlib/modules/BlockReward.move
  vm/stdlib/modules/TransactionManager.move
  vm/stdlib/modules/doc/Account.md
  vm/stdlib/modules/doc/BlockReward.md
  vm/stdlib/modules/doc/TransactionManager.md
  vm/stdlib/transaction_scripts/create_account.move
  vm/stdlib/transaction_scripts/doc/create_account.md
  vm/stdlib/transaction_scripts/doc/peer_to_peer.md
  vm/stdlib/transaction_scripts/doc/peer_to_peer_with_metadata.md
  vm/stdlib/transaction_scripts/peer_to_peer.move
  vm/stdlib/transaction_scripts/peer_to_peer_with_metadata.move
  vm/transaction-builder-generator/tests/generation.rs
  vm/transaction-builder/src/lib.rs
  vm/types/src/block_metadata.rs
  vm/types/src/proptest_types.rs
  vm/vm-runtime/src/starcoin_vm.rs
Labels: ready_to_merge

#1512 update on cli in order to make multisig txn doc work
  cmd/starcoin/src/account/show_cmd.rs
  cmd/starcoin/src/dev/derive_account_address_cmd.rs
  cmd/starcoin/src/view.rs
Labels: ready_to_merge

#1525 [release]fix windows build error
  devtools/x/src/main.rs
Labels: ready_to_merge

#1524 [spec] add spec for Math::mul_div() and related methods
  vm/functional-tests/tests/testsuite/math/mul_div.move
  vm/stdlib/modules/Account.move
  vm/stdlib/modules/ConsensusConfig.move
  vm/stdlib/modules/Epoch.move
  vm/stdlib/modules/Math.move
  vm/stdlib/modules/Token.move
  vm/stdlib/modules/doc/Account.md
  vm/stdlib/modules/doc/ConsensusConfig.md
  vm/stdlib/modules/doc/Epoch.md
  vm/stdlib/modules/doc/Math.md
  vm/stdlib/modules/doc/Token.md
Labels: ready_to_merge

#1526 [stdlib] Fix typo in PackageTxnManager.move and the corresponding PackageTxnManager.md
  vm/stdlib/modules/PackageTxnManager.move
  vm/stdlib/modules/doc/PackageTxnManager.md
Labels: ready_to_merge

#1528 [stdlib]Spec for TxnManager & TxnPublishOption & TxnTimeoutConfig.
  vm/stdlib/modules/Account.move
  vm/stdlib/modules/Block.move
  vm/stdlib/modules/Config.move
  vm/stdlib/modules/PackageTxnManager.move
  vm/stdlib/modules/TransactionManager.move
  vm/stdlib/modules/TransactionPublishOption.move
  vm/stdlib/modules/TransactionTimeout.move
  vm/stdlib/modules/TransactionTimeoutConfig.move
  vm/stdlib/modules/doc/Account.md
  vm/stdlib/modules/doc/Block.md
  vm/stdlib/modules/doc/Config.md
  vm/stdlib/modules/doc/PackageTxnManager.md
  vm/stdlib/modules/doc/TransactionManager.md
  vm/stdlib/modules/doc/TransactionPublishOption.md
  vm/stdlib/modules/doc/TransactionTimeout.md
  vm/stdlib/modules/doc/TransactionTimeoutConfig.md
Labels: auto_merge_failed, ready_to_merge

#1543 [stdlib] Fix some todo and do clean up
  core/genesis/generated/halley/genesis
  core/genesis/generated/main/genesis
  vm/functional-tests/tests/testsuite/incubator/SortedLinkedList.move
  vm/functional-tests/tests/testsuite/incubator/TokenLockPool.move
  vm/functional-tests/tests/testsuite/list/NameService.move
  vm/functional-tests/tests/testsuite/list/SortedLinkedList.move
  vm/functional-tests/tests/testsuite/package_txn_manager/package_txn_manager.move
  vm/functional-tests/tests/testsuite/tokenlockpool/fixed_lock.move
  vm/functional-tests/tests/testsuite/tokenlockpool/linear_lock.move
  vm/functional-tests/tests/testsuite/tokenlockpool/linear_lock_big_time.move
  vm/stdlib/compiled/latest/error_descriptions/error_descriptions.errmap
  vm/stdlib/compiled/latest/init_scripts/genesis_init.mv
  vm/stdlib/compiled/latest/stdlib/17_PackageTxnManager.mv
  vm/stdlib/compiled/latest/stdlib/21_TransactionPublishOption.mv
  vm/stdlib/compiled/latest/stdlib/36_DummyToken.mv
  vm/stdlib/compiled/latest/stdlib/43_SortedLinkedList.mv
  vm/stdlib/compiled/latest/stdlib/43_TransactionTimeout.mv
  vm/stdlib/compiled/latest/stdlib/44_TokenLockPool.mv
  vm/stdlib/compiled/latest/stdlib/44_TransactionManager.mv
  vm/stdlib/init_scripts/genesis_init.move
  vm/stdlib/modules/DummyToken.move
  vm/stdlib/modules/PackageTxnManager.move
  vm/stdlib/modules/SortedLinkedList.move
  vm/stdlib/modules/TransactionPublishOption.move
  vm/stdlib/modules/doc/DummyToken.md
  vm/stdlib/modules/doc/PackageTxnManager.md
  vm/stdlib/modules/doc/SortedLinkedList.md
  vm/stdlib/modules/doc/TokenLockPool.md
  vm/stdlib/modules/doc/TransactionPublishOption.md
  vm/stdlib/transaction_scripts/doc/genesis_init.md
Labels: ready_to_merge

#1546 [stdlib] on chain config by dao
  executor/src/stdlib_test/mod.rs
  executor/src/stdlib_test/module_upgrade_test.rs
  executor/src/stdlib_test/on_chain_config_test.rs
Labels: ready_to_merge

#1549 [consensus]window.
  consensus/src/difficulty.rs
Labels: ready_to_merge

#1548 improve dao spec
  core/genesis/generated/halley/genesis
  core/genesis/generated/main/genesis
  vm/stdlib/compiled/latest/stdlib/13_Config.mv
  vm/stdlib/compiled/latest/stdlib/18_Dao.mv
  vm/stdlib/modules/Config.move
  vm/stdlib/modules/Dao.move
  vm/stdlib/modules/doc/Config.md
  vm/stdlib/modules/doc/Dao.md
Labels: ready_to_merge
