Repository starcoinorg/starcoin, pull requests merged in 2020-11, with the labels that each got.

#1574 [jsonrpc] Rename NodeInfo now to now_seconds to avoid misuse.
  cmd/starcoin/src/account/accept_token_cmd.rs
  cmd/starcoin/src/account/execute_builtin_script_cmd.rs
  cmd/starcoin/src/account/transfer_cmd.rs
  cmd/starcoin/src/dev/deploy_cmd.rs
  cmd/starcoin/src/dev/execute_cmd.rs
  cmd/starcoin/src/dev/generate_multisig_txn_cmd.rs
  cmd/starcoin/src/dev/get_coin_cmd.rs
  cmd/starcoin/src/dev/upgrade_stdlib_cmd.rs
  cmd/starcoin/src/view.rs
  rpc/api/src/node/mod.rs
  testsuite/tests/steps/transaction.rs
Labels: ready_to_merge

#1575 [deploy] add docker build task
  .github/workflows/docker_build.yml
Labels: ready_to_merge

#1576 [stdlib & cmd]Stdlib upgrade
  Cargo.lock
  cmd/starcoin/src/debug/mod.rs
  cmd/starcoin/src/debug/sleep_cmd.rs
  cmd/starcoin/src/dev/mod.rs
  cmd/starcoin/src/dev/sign_txn_helper.rs
  cmd/starcoin/src/dev/upgrade_module_exe_cmd.rs
  cmd/starcoin/src/dev/upgrade_module_plan_cmd.rs
  cmd/starcoin/src/dev/upgrade_module_proposal_cmd.rs
  cmd/starcoin/src/dev/upgrade_module_queue_cmd.rs
  cmd/starcoin/src/dev/upgrade_stdlib_cmd.rs
  cmd/starcoin/src/lib.rs
  rpc/api/src/debug/mod.rs
  rpc/client/src/lib.rs
  rpc/server/src/module/debug_rpc.rs
  vm/stdlib/src/lib.rs
  vm/stdlib/src/main.rs
  vm/transaction-builder/Cargo.toml
  vm/transaction-builder/src/lib.rs
  vm/types/src/dao_config.rs
Labels: ready_to_merge

#1579 unify binary serde-json to hex string with 0x
  Cargo.lock
  Cargo.toml
  cmd/starcoin/Cargo.toml
  cmd/starcoin/src/chain/get_block_cmd.rs
  cmd/starcoin/src/chain/get_events_cmd.rs
  cmd/starcoin/src/chain/get_txn_by_block_cmd.rs
  cmd/starcoin/src/chain/get_txn_cmd.rs
  cmd/starcoin/src/chain/get_txn_info_cmd.rs
  cmd/starcoin/src/debug/get_block_by_uncle.rs
  cmd/starcoin/src/dev/derive_account_address_cmd.rs
  cmd/starcoin/src/dev/generate_multisig_txn_cmd.rs
  cmd/starcoin/src/dev/subscribe_cmd.rs
  commons/crypto/Cargo.toml
  commons/crypto/src/lib.rs
  commons/proptest-helpers/Cargo.toml
  commons/scs/Cargo.toml
  commons/serde-helpers/Cargo.toml
  commons/serde-helpers/src/lib.rs
  config/Cargo.toml
  consensus/Cargo.toml
  core/genesis/Cargo.toml
  dataformat-generator/build.rs
  devtools/x/Cargo.toml
  executor/Cargo.toml
  rpc/api/Cargo.toml
  rpc/api/src/types/contract_call.rs
  rpc/server/src/module/pubsub/tests.rs
  testsuite/features/cmd.feature
  testsuite/tests/steps/cmd.rs
  vm/compiler/Cargo.toml
  vm/functional-tests/Cargo.toml
  vm/move-coverage/Cargo.toml
  vm/move-explain/Cargo.toml
  vm/move-prover/Cargo.toml
  vm/stdlib/Cargo.toml
  vm/transaction-builder-generator/Cargo.toml
  vm/types/Cargo.toml
  vm/types/src/access_path.rs
  vm/types/src/event.rs
  vm/types/src/transaction/authenticator.rs
  vm/types/src/transaction/module.rs
  vm/types/src/transaction/script.rs
  vm/vm-runtime/Cargo.toml
Labels: ready_to_merge

#1581 [accumulator] Fix accumulator get_leaves return order and append result.
  chain/open-block/src/lib.rs
  chain/src/chain.rs
  chain/src/tests/block_test_utils.rs
  core/accumulator/src/accumulator_test.rs
  core/accumulator/src/lib.rs
  core/genesis/src/lib.rs
Labels: ready_to_merge

#1589 test_upgrade_module
  Cargo.lock
  cmd/starcoin/Cargo.toml
  cmd/starcoin/src/dev/sign_txn_helper.rs
  rpc/server/src/module/debug_rpc.rs
Labels: ready_to_merge

#1588 Feature/stream task and sync
  Cargo.lock
  Cargo.toml
  chain/mock/src/mock_chain.rs
  chain/src/chain.rs
  commons/stream-task/Cargo.toml
  commons/stream-task/src/collector.rs
  commons/stream-task/src/event.rs
  commons/stream-task/src/generator.rs
  commons/stream-task/src/lib.rs
  commons/stream-task/src/task_stream.rs
  network/api/Cargo.toml
  network/api/src/peer_provider.rs
  sync/Cargo.toml
  sync/src/block_sync/mod.rs
  sync/src/download.rs
  sync/src/lib.rs
  sync/src/sync2.rs
  sync/src/task.rs
  sync/src/tasks/accumulator_sync_task.rs
  sync/src/tasks/block_sync_task.rs
  sync/src/tasks/find_ancestor_task.rs
  sync/src/tasks/mock.rs
  sync/src/tasks/mod.rs
  sync/src/tasks/tests.rs
  sync/src/verified_rpc_client.rs
  sync/tests/accumulator_sync_test.rs
  types/src/block.rs
  vm/types/src/on_chain_resource/global_time.rs
Labels: ready_to_merge

#1596 [sync] Finished new sync service and refactor WriteChainService.
  chain/api/src/errors.rs
  chain/api/src/message.rs
  chain/api/src/service.rs
  chain/chain-notify/src/lib.rs
  chain/mock/src/mock_chain.rs
  chain/service/src/chain_service.rs
  chain/src/chain.rs
  cmd/starcoin/src/chain/branchs_cmd.rs
  cmd/starcoin/src/chain/mod.rs
  cmd/starcoin/src/lib.rs
  commons/service-registry/src/bus/service.rs
  commons/service-registry/src/bus/sys_bus.rs
  commons/stream-task/src/collector.rs
  commons/stream-task/src/event.rs
  commons/stream-task/src/lib.rs
  core/accumulator/src/lib.rs
  miner/src/create_block_template/mod.rs
  miner/src/headblock_pacemaker.rs
  miner/src/lib.rs
  miner/src/ondemand_pacemaker.rs
  miner/src/task.rs
  node/src/node.rs
  rpc/api/src/chain/mod.rs
  rpc/client/src/lib.rs
  rpc/server/src/module/chain_rpc.rs
  rpc/server/src/module/pubsub/tests.rs
  sync/src/block_connector/block_connector_service.rs
  sync/src/block_connector/mod.rs
  sync/src/block_connector/write_block_chain.rs
  sync/src/block_sync/mod.rs
  sync/src/download.rs
  sync/src/lib.rs
  sync/src/sync2.rs
  sync/src/tasks/accumulator_sync_task.rs
  sync/src/tasks/block_sync_task.rs
  sync/src/tasks/find_ancestor_task.rs
  sync/src/tasks/mock.rs
  sync/src/tasks/mod.rs
  sync/src/tasks/tests.rs
  sync/src/txn_sync/mod.rs
  sync/tests/accumulator_sync_test.rs
  sync/tests/full_sync_test.rs
  sync/tests/txn_sync_test.rs
  testsuite/features/cmd.feature
  txpool/src/lib.rs
  txpool/src/pool/verifier.rs
  txpool/src/pool_client.rs
  types/src/block.rs
  types/src/lib.rs
  types/src/node_status.rs
  types/src/startup_info.rs
  types/src/system_events.rs
  vm/vm-runtime/src/errors.rs
Labels: ready_to_merge

#1601 unify from str
  Cargo.lock
  account/api/src/types.rs
  account/lib/src/account.rs
  account/lib/src/account_manager.rs
  account/lib/src/account_storage.rs
  account/lib/src/account_test.rs
  account/service/src/service.rs
  cmd/starcoin/Cargo.toml
  cmd/starcoin/src/account/accept_token_cmd.rs
  cmd/starcoin/src/account/default_cmd.rs
  cmd/starcoin/src/account/execute_builtin_script_cmd.rs
  cmd/starcoin/src/account/export_cmd.rs
  cmd/starcoin/src/account/import_cmd.rs
  cmd/starcoin/src/account/lock_cmd.rs
  cmd/starcoin/src/account/partial_sign_txn_cmd.rs
  cmd/starcoin/src/account/show_cmd.rs
  cmd/starcoin/src/account/transfer_cmd.rs
  cmd/starcoin/src/account/unlock_cmd.rs
  cmd/starcoin/src/chain/get_block_cmd.rs
  cmd/starcoin/src/chain/get_events_cmd.rs
  cmd/starcoin/src/chain/get_txn_by_block_cmd.rs
  cmd/starcoin/src/chain/get_txn_cmd.rs
  cmd/starcoin/src/chain/get_txn_info_cmd.rs
  cmd/starcoin/src/debug/get_block_by_uncle.rs
  cmd/starcoin/src/dev/call_contract_cmd.rs
  cmd/starcoin/src/dev/compile_cmd.rs
  cmd/starcoin/src/dev/derive_account_address_cmd.rs
  cmd/starcoin/src/dev/execute_cmd.rs
  cmd/starcoin/src/dev/generate_multisig_txn_cmd.rs
  cmd/starcoin/src/dev/subscribe_cmd.rs
  cmd/starcoin/src/state/get_cmd.rs
  cmd/starcoin/src/state/get_proof_cmd.rs
  commons/crypto/Cargo.toml
  commons/crypto/src/lib.rs
  commons/crypto/src/multi_ed25519/multi_shard.rs
  commons/proptest-helpers/Cargo.toml
  commons/scs/Cargo.toml
  config/Cargo.toml
  devtools/x/Cargo.toml
  rustfmt.toml
  vm/compiler/Cargo.toml
  vm/functional-tests/Cargo.toml
  vm/functional-tests/src/preprocessor.rs
  vm/move-coverage/Cargo.toml
  vm/move-explain/Cargo.toml
  vm/move-prover/Cargo.toml
  vm/stdlib/Cargo.toml
  vm/transaction-builder-generator/Cargo.toml
  vm/types/Cargo.toml
  vm/types/src/event.rs
  vm/types/src/transaction/authenticator.rs
  vm/vm-runtime/Cargo.toml
Labels: ready_to_merge

#1605 [cmd] fix format table result for vec types
  Cargo.lock
  commons/scmd/Cargo.toml
  commons/scmd/src/result.rs
Labels: ready_to_merge

#1612 [stress test] fix tx-factory crash when account_num is less than TXN_…
  cmd/tx-factory/src/main.rs
Labels: ready_to_merge

#1616 Feature/epoch time update
  chain/src/tests/test_epoch_switch.rs
  cmd/starcoin/src/state/get_cmd.rs
  consensus/src/difficulty.rs
  consensus/src/dummy.rs
  core/accumulator/src/accumulator_test.rs
  core/forkable-jellyfish-merkle/src/node_type/node_type_test.rs
  core/genesis/generated/halley/genesis
  core/genesis/generated/main/genesis
  core/genesis/generated/proxima/genesis
  devtools/x/src/main.rs
  test-helper/src/dao.rs
  txpool/src/pool/local_transactions.rs
  vm/functional-tests/tests/testsuite/epoch/adjust_epoch_block_time_max.move
  vm/functional-tests/tests/testsuite/epoch/adjust_epoch_block_time_min.move
  vm/functional-tests/tests/testsuite/epoch/epoch_compute.move
  vm/stdlib/modules/Epoch.move
  vm/types/src/genesis_config.rs
  vm/types/src/on_chain_resource/epoch.rs
Labels: auto_merge_failed, ready_to_merge

#1609 Refactor consensus && miner solver
  Cargo.lock
  cmd/miner_client/Cargo.toml
  cmd/miner_client/src/cpu_solver.rs
  cmd/miner_client/src/job_client.rs
  cmd/miner_client/src/lib.rs
  cmd/miner_client/src/main.rs
  cmd/miner_client/src/miner.rs
  cmd/miner_client/src/solver.rs
  cmd/miner_client/src/worker.rs
  config/src/miner_config.rs
  consensus/cryptonight-rs/src/lib.rs
  consensus/src/argon.rs
  consensus/src/cn.rs
  consensus/src/consensus.rs
  consensus/src/consensus_test.rs
  consensus/src/difficulty.rs
  consensus/src/dummy.rs
  consensus/src/keccak.rs
  consensus/src/lib.rs
  core/genesis/generated/halley/genesis
  core/genesis/generated/main/genesis
  core/genesis/generated/proxima/genesis
  miner/src/job_bus_client.rs
  miner/src/lib.rs
  miner/src/task.rs
  miner/tests/miner_test.rs
  rpc/api/src/miner.rs
  rpc/api/src/types/pubsub.rs
  rpc/client/src/lib.rs
  rpc/server/src/module/miner_rpc.rs
  rpc/server/src/module/pubsub.rs
  rpc/server/src/module/pubsub/tests.rs
  types/src/block.rs
  types/src/system_events.rs
  vm/types/src/genesis_config.rs
Labels: auto_merge_failed, break, ready_to_merge

#1618 [cleanup] Cleanup startup info's field.
  core/genesis/src/lib.rs
  kube/manifest/starcoin.yaml
  sync/src/block_connector/write_block_chain.rs
  types/src/startup_info.rs
Labels: ready_to_merge

#1632 fix console error sometimes
  cmd/starcoin/src/account/execute_builtin_script_cmd.rs
  cmd/starcoin/src/dev/call_contract_cmd.rs
  cmd/starcoin/src/dev/compile_cmd.rs
  cmd/starcoin/src/dev/execute_cmd.rs
  cmd/starcoin/src/dev/generate_multisig_txn_cmd.rs
  cmd/starcoin/src/dev/subscribe_cmd.rs
Labels: ready_to_merge

#1630 [network] Optimize network and block-relay event process logic
  Cargo.lock
  block-relayer/src/block_relayer.rs
  network/api/Cargo.toml
  network/api/src/lib.rs
  network/api/src/peer_message_handler.rs
  network/src/network.rs
  network/tests/network_rpc_test.rs
  node/Cargo.toml
  node/src/lib.rs
  node/src/node.rs
  node/src/peer_message_handler.rs
  sync/src/block_connector/block_connector_service.rs
  sync/src/sync2.rs
  test-helper/Cargo.toml
  test-helper/src/network.rs
  txpool/src/lib.rs
Labels: ready_to_merge

#1631 [script]Add update_module_upgrade_strategy script.
  core/genesis/generated/halley/genesis
  core/genesis/generated/main/genesis
  core/genesis/generated/proxima/genesis
  vm/stdlib/compiled/latest/stdlib/13_Config.mv
  vm/stdlib/compiled/latest/transaction_scripts/abi/rotate_authentication_key.abi
  vm/stdlib/compiled/latest/transaction_scripts/abi/update_module_upgrade_strategy.abi
  vm/stdlib/compiled/latest/transaction_scripts/rotate_authentication_key.mv
  vm/stdlib/compiled/latest/transaction_scripts/update_module_upgrade_strategy.mv
  vm/stdlib/modules/Config.move
  vm/stdlib/modules/PackageTxnManager.move
  vm/stdlib/modules/doc/Config.md
  vm/stdlib/modules/doc/Dao.md
  vm/stdlib/modules/doc/MintDaoProposal.md
  vm/stdlib/modules/doc/ModifyDaoConfigProposal.md
  vm/stdlib/modules/doc/OnChainConfigDao.md
  vm/stdlib/src/transaction_scripts.rs
  vm/stdlib/transaction_scripts/doc/rotate_authentication_key.md
  vm/stdlib/transaction_scripts/doc/update_module_upgrade_strategy.md
  vm/stdlib/transaction_scripts/rotate_authentication_key.move
  vm/stdlib/transaction_scripts/update_module_upgrade_strategy.move
Labels: auto_merge_failed, break, ready_to_merge

#1635 kube: Use pv storage
  cmd/miner_client/src/solver.rs
  docker/Dockerfile
  kube/manifest/starcoin.yaml
  kube/opt/set_default_storageclass_aliyun.sh
Labels: ready_to_merge

#1620 Feature/dao destroy fix
  core/genesis/generated/halley/genesis
  core/genesis/generated/main/genesis
  core/genesis/generated/proxima/genesis
  scripts/move_prover.sh
  vm/functional-tests/tests/testsuite/dao/test_dao_failure.move
  vm/stdlib/compiled/latest/error_descriptions/error_descriptions.errmap
  vm/stdlib/compiled/latest/stdlib/18_Dao.mv
  vm/stdlib/compiled/latest/stdlib/19_UpgradeModuleDaoProposal.mv
  vm/stdlib/compiled/latest/stdlib/23_OnChainConfigDao.mv
  vm/stdlib/compiled/latest/stdlib/24_ModifyDaoConfigProposal.mv
  vm/stdlib/compiled/latest/stdlib/39_MintDaoProposal.mv
  vm/stdlib/compiled/latest/transaction_scripts/abi/cast_vote.abi
  vm/stdlib/compiled/latest/transaction_scripts/abi/destroy_terminated_proposal.abi
  vm/stdlib/compiled/latest/transaction_scripts/abi/queue_proposal_action.abi
  vm/stdlib/compiled/latest/transaction_scripts/abi/revoke_vote.abi
  vm/stdlib/compiled/latest/transaction_scripts/abi/unstake_vote.abi
  vm/stdlib/compiled/latest/transaction_scripts/cast_vote.mv
  vm/stdlib/compiled/latest/transaction_scripts/destroy_terminated_proposal.mv
  vm/stdlib/compiled/latest/transaction_scripts/queue_proposal_action.mv
  vm/stdlib/compiled/latest/transaction_scripts/revoke_vote.mv
  vm/stdlib/compiled/latest/transaction_scripts/unstake_vote.mv
  vm/stdlib/modules/Dao.move
  vm/stdlib/modules/doc/Dao.md
  vm/stdlib/transaction_scripts/cast_vote.move
  vm/stdlib/transaction_scripts/destroy_terminated_proposal.move
  vm/stdlib/transaction_scripts/doc/cast_vote.md
  vm/stdlib/transaction_scripts/doc/destroy_terminated_proposal.md
  vm/stdlib/transaction_scripts/doc/queue_proposal_action.md
  vm/stdlib/transaction_scripts/doc/revoke_vote.md
  vm/stdlib/transaction_scripts/doc/unstake_vote.md
  vm/stdlib/transaction_scripts/queue_proposal_action.move
  vm/stdlib/transaction_scripts/revoke_vote.move
  vm/stdlib/transaction_scripts/unstake_vote.move
Labels: ready_to_merge

#1617 [cli] add command to show tps for given epoch
  chain/api/src/chain.rs
  chain/api/src/message.rs
  chain/api/src/service.rs
  chain/service/src/chain_service.rs
  chain/src/chain.rs
  cmd/starcoin/src/chain/mod.rs
  cmd/starcoin/src/chain/tps.rs
  cmd/starcoin/src/lib.rs
  rpc/api/src/chain/mod.rs
  rpc/client/src/lib.rs
  rpc/server/src/module/chain_rpc.rs
  types/src/lib.rs
  types/src/stress_test.rs
Labels: ready_to_merge

#1561 [stdlib|vm-runtime] Fix typos
  core/genesis/generated/halley/genesis
  core/genesis/generated/main/genesis
  core/genesis/generated/proxima/genesis
  vm/functional-tests/tests/testsuite/incubator/TokenLockPool.move
  vm/stdlib/compiled/latest/error_descriptions/error_descriptions.errmap
  vm/stdlib/compiled/latest/stdlib/11_Token.mv
  vm/stdlib/compiled/latest/stdlib/13_Config.mv
  vm/stdlib/compiled/latest/stdlib/17_PackageTxnManager.mv
  vm/stdlib/compiled/latest/stdlib/32_Box.mv
  vm/stdlib/compiled/latest/stdlib/35_ConsensusStrategy.mv
  vm/stdlib/modules/Box.move
  vm/stdlib/modules/Compare.move
  vm/stdlib/modules/Config.move
  vm/stdlib/modules/ConsensusStrategy.move
  vm/stdlib/modules/Dao.move
  vm/stdlib/modules/Event.move
  vm/stdlib/modules/ModifyDaoConfigProposal.move
  vm/stdlib/modules/Offer.move
  vm/stdlib/modules/PackageTxnManager.move
  vm/stdlib/modules/Signer.move
  vm/stdlib/modules/Token.move
  vm/stdlib/modules/UpgradeModuleDaoProposal.move
  vm/stdlib/modules/doc/Box.md
  vm/stdlib/modules/doc/Compare.md
  vm/stdlib/modules/doc/Config.md
  vm/stdlib/modules/doc/ConsensusStrategy.md
  vm/stdlib/modules/doc/Dao.md
  vm/stdlib/modules/doc/Event.md
  vm/stdlib/modules/doc/ModifyDaoConfigProposal.md
  vm/stdlib/modules/doc/Offer.md
  vm/stdlib/modules/doc/PackageTxnManager.md
  vm/stdlib/modules/doc/Token.md
  vm/vm-runtime/src/errors.rs
Labels: auto_merge_failed, break, ready_to_merge

#1641 Change the params of network rpc apis from usize to u64
  chain/api/src/chain.rs
  chain/api/src/message.rs
  chain/api/src/service.rs
  chain/service/src/chain_service.rs
  chain/src/chain.rs
  core/accumulator/src/lib.rs
  network-rpc/api/src/lib.rs
  sync/src/download.rs
  sync/src/helper.rs
  sync/src/tasks/accumulator_sync_task.rs
  sync/src/tasks/block_sync_task.rs
  sync/src/tasks/find_ancestor_task.rs
  sync/src/tasks/mock.rs
  sync/src/tasks/mod.rs
  sync/src/verified_rpc_client.rs
Labels: break, ready_to_merge

#1640 [script]Mint token script
  core/genesis/generated/halley/genesis
  core/genesis/generated/main/genesis
  core/genesis/generated/proxima/genesis
  vm/stdlib/compiled/latest/stdlib/11_Token.mv
  vm/stdlib/compiled/latest/transaction_scripts/abi/mint_token_by_fix_key.abi
  vm/stdlib/compiled/latest/transaction_scripts/abi/mint_token_by_linear_key.abi
  vm/stdlib/compiled/latest/transaction_scripts/mint_token_by_fix_key.mv
  vm/stdlib/compiled/latest/transaction_scripts/mint_token_by_linear_key.mv
  vm/stdlib/modules/Token.move
  vm/stdlib/modules/doc/Token.md
  vm/stdlib/modules/doc/UpgradeModuleDaoProposal.md
  vm/stdlib/src/transaction_scripts.rs
  vm/stdlib/transaction_scripts/doc/mint_token_by_fix_key.md
  vm/stdlib/transaction_scripts/doc/mint_token_by_linear_key.md
  vm/stdlib/transaction_scripts/mint_token_by_fix_key.move
  vm/stdlib/transaction_scripts/mint_token_by_linear_key.move
Labels: auto_merge_failed, break, ready_to_merge

#1642 [stdlib] modify error_code for voted to others already
  core/genesis/generated/halley/genesis
  core/genesis/generated/main/genesis
  core/genesis/generated/proxima/genesis
  vm/stdlib/compiled/latest/error_descriptions/error_descriptions.errmap
  vm/stdlib/compiled/latest/stdlib/18_Dao.mv
  vm/stdlib/modules/Dao.move
  vm/stdlib/modules/doc/Dao.md
Labels: ready_to_merge

#1636 [cli] show more details of txpool status
  txpool/api/src/lib.rs
  txpool/src/pool/queue.rs
Labels: ready_to_merge

#1643 [network] Add some command to manage network and change network init config
  cmd/starcoin/src/lib.rs
  cmd/starcoin/src/node/mod.rs
  cmd/starcoin/src/node/network/add_peer_cmd.rs
  cmd/starcoin/src/node/network/connected_peers_cmd.rs
  cmd/starcoin/src/node/network/get_address_cmd.rs
  cmd/starcoin/src/node/network/mod.rs
  network-p2p/src/metrics.rs
  network-rpc/derive/src/to_client.rs
  network/src/net.rs
  network/src/net_test.rs
  network/src/network.rs
  node/src/rpc_service_factory.rs
  rpc/api/src/lib.rs
  rpc/api/src/network_manager.rs
  rpc/client/src/lib.rs
  rpc/server/src/module/mod.rs
  rpc/server/src/module/network_manager_rpc.rs
  rpc/server/src/service.rs
  types/src/peer_info.rs
Labels: ready_to_merge

#1644 [vm]Check strategy when upgrade module.
  vm/types/src/account_config/resources/mod.rs
  vm/types/src/account_config/resources/module_upgrade_strategy.rs
  vm/vm-runtime/src/starcoin_vm.rs
Labels: auto_merge_failed, ready_to_merge

#1645 kube: Clean some useless codes
  docker/Dockerfile
  kube/manifest/service.yaml
  kube/manifest/starcoin.yaml
  kube/opt/nodes_info.sh
Labels: ready_to_merge

#1648 [test]test_only_new_module
  cmd/starcoin/src/dev/sign_txn_helper.rs
  core/genesis/src/lib.rs
  vm/types/src/account_config/resources/module_upgrade_strategy.rs
Labels: ready_to_merge

#1652 [stdlib]Add mint_and_split_by_linear_key.
  core/genesis/generated/halley/genesis
  core/genesis/generated/main/genesis
  core/genesis/generated/proxima/genesis
  vm/stdlib/compiled/latest/error_descriptions/error_descriptions.errmap
  vm/stdlib/compiled/latest/stdlib/11_Token.mv
  vm/stdlib/compiled/latest/transaction_scripts/abi/mint_and_split_by_linear_key.abi
  vm/stdlib/compiled/latest/transaction_scripts/mint_and_split_by_linear_key.mv
  vm/stdlib/modules/Token.move
  vm/stdlib/modules/doc/PackageTxnManager.md
  vm/stdlib/modules/doc/Token.md
  vm/stdlib/src/transaction_scripts.rs
  vm/stdlib/transaction_scripts/doc/mint_and_split_by_linear_key.md
  vm/stdlib/transaction_scripts/mint_and_split_by_linear_key.move
Labels: break, ready_to_merge

#1664 rename master to main.
  benchmarks/src/chain.rs
  chain/api/src/message.rs
  chain/api/src/service.rs
  chain/mock/src/mock_chain.rs
  chain/service/src/chain_service.rs
  chain/src/chain.rs
  chain/src/tests/test_block_chain.rs
  cmd/generator/src/gen_data.rs
  cmd/starcoin/src/chain/epoch_info.rs
  cmd/starcoin/src/chain/get_epoch_info_by_number.rs
  cmd/starcoin/src/chain/get_global_time_by_number.rs
  core/genesis/src/lib.rs
  miner/src/create_block_template/mod.rs
  miner/src/create_block_template/test_create_block_template.rs
  network-rpc/src/rpc.rs
  network/src/network.rs
  node/src/lib.rs
  node/tests/test_node_run.rs
  rpc/server/src/module/chain_rpc.rs
  rpc/server/src/module/pubsub/tests.rs
  state/service/src/service.rs
  sync/src/block_connector/test_illegal_block.rs
  sync/src/block_connector/test_write_block_chain.rs
  sync/src/block_connector/write_block_chain.rs
  sync/src/download.rs
  sync/src/sync2.rs
  sync/tests/full_sync_test.rs
  sync/tests/test_sync/mod.rs
  test-helper/src/chain.rs
  txpool/src/lib.rs
  txpool/src/test.rs
  types/src/startup_info.rs
  vm/functional-tests/src/config/transaction.rs
  vm/move-prover/src/prover_task_runner.rs
Labels: break, ready_to_merge

#1665 Proposal info
  core/genesis/generated/halley/genesis
  core/genesis/generated/main/genesis
  core/genesis/generated/proxima/genesis
  vm/stdlib/compiled/latest/stdlib/18_Dao.mv
  vm/stdlib/modules/Dao.move
  vm/stdlib/modules/doc/Dao.md
Labels: break, ready_to_merge

#1667 [functional-tests]split_fixed_key & split_linear_key
  vm/functional-tests/tests/testsuite/token/split_fixed_key.move
  vm/functional-tests/tests/testsuite/token/split_linear_key.move
Labels: ready_to_merge

#1675 stdlib: fix token code
  account/service/src/account_events.rs
  cmd/starcoin/src/view.rs
  core/genesis/generated/halley/genesis
  core/genesis/generated/main/genesis
  core/genesis/generated/proxima/genesis
  vm/functional-tests/tests/testsuite/check/gas_used_out.move
  vm/stdlib/compiled/latest/stdlib/08_Math.mv
  vm/stdlib/compiled/latest/stdlib/09_SCS.mv
  vm/stdlib/compiled/latest/stdlib/11_Token.mv
  vm/stdlib/compiled/latest/stdlib/30_Account.mv
  vm/stdlib/modules/Account.move
  vm/stdlib/modules/Token.move
  vm/stdlib/modules/doc/Account.md
  vm/stdlib/modules/doc/Token.md
  vm/types/src/account_config/events/accept_token_payment.rs
  vm/types/src/account_config/events/account_deposit.rs
  vm/types/src/account_config/events/account_withdraw.rs
  vm/types/src/account_config/events/burn.rs
  vm/types/src/account_config/events/mint.rs
  vm/types/src/token/token_code.rs
Labels: ready_to_merge

#1679 [vm] upgrade move coverage tool
  Cargo.lock
  cmd/starcoin/Cargo.toml
  commons/crypto/Cargo.toml
  commons/proptest-helpers/Cargo.toml
  commons/scs/Cargo.toml
  config/Cargo.toml
  devtools/x/Cargo.toml
  vm/compiler/Cargo.toml
  vm/functional-tests/Cargo.toml
  vm/move-coverage/Cargo.toml
  vm/move-coverage/check_coverage.bash
  vm/move-coverage/src/bin/coverage-summaries.rs
  vm/move-coverage/src/bin/move-trace-conversion.rs
  vm/move-coverage/src/coverage_map.rs
  vm/move-coverage/src/source_coverage.rs
  vm/move-coverage/src/summary.rs
  vm/move-explain/Cargo.toml
  vm/move-prover/Cargo.toml
  vm/stdlib/Cargo.toml
  vm/transaction-builder-generator/Cargo.toml
  vm/types/Cargo.toml
  vm/vm-runtime/Cargo.toml
Labels: ready_to_merge

#1678 [cmd & chain]Add uncle_path cmd.
  chain/api/src/message.rs
  chain/api/src/service.rs
  chain/service/src/chain_service.rs
  cmd/starcoin/src/chain/get_epoch_uncles_by_number.rs
  cmd/starcoin/src/chain/mod.rs
  cmd/starcoin/src/chain/uncle_path.rs
  rpc/api/src/chain/mod.rs
  rpc/client/src/lib.rs
  rpc/server/src/module/chain_rpc.rs
Labels: ready_to_merge

#1696 [cmd & chain]Add epoch_uncle_summary_by_number cmd.
  chain/api/src/message.rs
  chain/api/src/service.rs
  chain/service/src/chain_service.rs
  cmd/starcoin/src/chain/mod.rs
  cmd/starcoin/src/chain/uncle/epoch_uncle_summary_by_number.rs
  cmd/starcoin/src/chain/uncle/list_epoch_uncles_by_number.rs
  cmd/starcoin/src/chain/uncle/mod.rs
  cmd/starcoin/src/chain/uncle/uncle_path.rs
  cmd/starcoin/src/lib.rs
  rpc/api/src/chain/mod.rs
  rpc/client/src/lib.rs
  rpc/server/src/module/chain_rpc.rs
  types/src/block.rs
Labels: ready_to_merge

#1695 [sync] Output target and peer info in sync progress report.
  cmd/starcoin/src/node/sync/progress_cmd.rs
  miner/src/lib.rs
  rpc/api/src/sync_manager.rs
  rpc/client/src/lib.rs
  rpc/server/src/module/sync_manager_rpc.rs
  sync/api/src/lib.rs
  sync/api/src/service.rs
  sync/src/sync2.rs
  sync/src/tasks/mod.rs
  sync/src/verified_rpc_client.rs
Labels: ready_to_merge

#1702 [sync] sync start cmd supports sync from specified peers.
  cmd/starcoin/src/node/sync/start_cmd.rs
  network/src/net.rs
  rpc/api/src/sync_manager.rs
  rpc/client/src/lib.rs
  rpc/server/src/module/sync_manager_rpc.rs
  sync/api/src/lib.rs
  sync/api/src/service.rs
  sync/src/block_connector/block_connector_service.rs
  sync/src/sync2.rs
Labels: ready_to_merge

#1706 [chain]rollback block size metric.
  sync/src/block_connector/metrics.rs
  sync/src/block_connector/write_block_chain.rs
Labels: ready_to_merge

#1716 Feature/docker update
  .github/workflows/docker_build.yml
Labels: ready_to_merge
