Repository starcoinorg/starcoin, pull requests merged in 2021-08, with the labels that each got.

#2802 [vm] Fix batch transfer ScriptFunction builder
  executor/tests/executor_test.rs
  vm/transaction-builder/src/lib.rs
Labels: area:vm, bugfix

#2820 fix error when decoding failed txn
  rpc/server/src/module/chain_rpc.rs
Labels: bugfix

#2818 implement node reset
  chain/api/src/chain.rs
  chain/service/src/chain_service.rs
  chain/src/chain.rs
  chain/tests/test_block_chain.rs
  cmd/starcoin/src/node/reset_cmd.rs
  node/api/src/message.rs
  node/api/src/node_service.rs
  node/src/node.rs
  rpc/api/src/node_manager.rs
  sync/src/block_connector/block_connector_service.rs
  sync/src/block_connector/mod.rs
  sync/src/block_connector/test_write_block_chain.rs
  sync/src/block_connector/write_block_chain.rs
  types/src/startup_info.rs
Labels: area:storage, area:chain

#2821 fix move check on remote state
  vm/move-cli/src/dependencies.rs
  vm/move-cli/src/lib.rs
  vm/move-cli/src/main.rs
  vm/move-cli/src/remote_state.rs
Labels: bugfix
