Repository starcoinorg/starcoin, pull requests merged in 2025-09, with the labels that each got.

#4675 Use env to control the job count for building and testing
  node/src/lib.rs
  node/tests/test_node_run.rs
  rpc/client/tests/client_server_test.rs
  scripts/nextest.sh
  sync/tests/full_sync_test.rs
  sync/tests/test_sync/mod.rs
Labels: ci-runner: jack

#4693 [CI mpm test] Added CI integration testing for Move package manager
  .github/workflows/build_test.yml
  scripts/move_test.sh
  scripts/nextest.sh
  vm2/framework/starcoin-framework/integration-tests/epoch/adjust_epoch_block_time_max.exp
  vm2/framework/starcoin-framework/integration-tests/epoch/adjust_epoch_block_time_min.exp
  vm2/framework/starcoin-framework/integration-tests/epoch/epoch_data.move
Labels: ci-runner: nixos-amd

#4676 Remove async std dep
  Cargo.lock
  Cargo.toml
  cmd/miner_client/Cargo.toml
  cmd/miner_client/src/stratum_client.rs
  cmd/peer-watcher/Cargo.toml
  cmd/peer-watcher/src/main.rs
  commons/service-registry/Cargo.toml
  commons/service-registry/src/bus/sys_bus.rs
  commons/stream-task/Cargo.toml
  commons/stream-task/src/collector.rs
  commons/stream-task/src/lib.rs
  commons/stream-task/src/tests.rs
  network-p2p/Cargo.toml
  network-p2p/src/protocol/generic_proto/upgrade/notifications.rs
  network-p2p/src/service.rs
  network-p2p/src/service_test.rs
  network-rpc/Cargo.toml
  network-rpc/src/tests.rs
  network/Cargo.toml
  network/tests/network_service_test.rs
  node/Cargo.toml
  node/src/lib.rs
  rpc/client/Cargo.toml
  rpc/client/src/lib.rs
  rpc/client/tests/client_server_test.rs
  sync/Cargo.toml
  sync/src/announcement/mod.rs
  sync/src/sync.rs
  sync/src/tasks/block_sync_task.rs
  sync/src/tasks/mock.rs
  sync/src/tasks/test_tools.rs
  sync/src/tasks/tests.rs
  sync/src/tasks/tests_dag.rs
  sync/tests/full_sync_test.rs
  sync/tests/test_sync/mod.rs
Labels: ci-runner: do

#4640 Add vm2 txn factory
  Cargo.lock
  cmd/tx-factory/Cargo.toml
  cmd/tx-factory/README2.md
  cmd/tx-factory/src/lib.rs
  cmd/tx-factory/src/vm2_txn_lib.rs
  cmd/tx-factory/src/vm2_txn_main.rs
  rpc/client/src/async_client.rs
  rpc/client/src/lib.rs
  rpc/client/src/remote_state_reader2/async_reader.rs
  rpc/client/src/remote_state_reader2/mod.rs
Labels: ci-runner: k8s
